#!/bin/bash

BLD_USER=builder

# Add user builder
echo "Adding user $BLD_USER:"
useradd $BLD_USER

# builder password
echo "$BLD_USER password:"
passwd $BLD_USER

# Add user groups
echo "Adding user groups:"
usermod -a -G wheel $BLD_USER
usermod -a -G video $BLD_USER
usermod -a -G input $BLD_USER

# chown 
echo "chown sources:"
chown -R $BLD_USER /sources

echo "chown /var/lib/jhalfs:"
chown -R $BLD_USER /var/lib/jhalfs

echo "chown /home/"
cp -r /home/blfs-builder /home/$BLD_USER
rm -rf /home/blfs-builder
chown -R $BLD_USER:$BLD_USER /home/$BLD_USER
