#!/bin/bash
set +h
set -e



PREV_SEC=${SECONDS}
      
ROOT=/

SCRIPT_ROOT=jhalfs

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
SECONDS=${PREV_SEC}

# Start of LFS book script
cd /etc/sysconfig/
cat > ifconfig.eth0 << "EOF"
ONBOOT=yes
IFACE=eth0
SERVICE=ipv4-static
IP=10.0.2.9
GATEWAY=10.0.2.2
PREFIX=24
BROADCAST=10.0.2.255
EOF
cat > /etc/resolv.conf << "EOF"
# Begin /etc/resolv.conf

domain local
nameserver 10.0.2.3
nameserver 8.8.8.8

# End /etc/resolv.conf
EOF
echo "newHost11.0" > /etc/hostname
cat > /etc/hosts << "EOF"
# Begin /etc/hosts

127.0.0.1 localhost.localdomain localhost
127.0.1.1 newHost11.0.local newHost11.0
10.0.2.9 newHost11.0.local newHost11.0 
::1       localhost ip6-localhost ip6-loopback
ff02::1   ip6-allnodes
ff02::2   ip6-allrouters

# End /etc/hosts
EOF
echo -e "\n\nTotalseconds: $SECONDS\n"

# End of LFS book script

echo "KB: $(du -skx --exclude=lost+found --exclude=var/lib --exclude=$SCRIPT_ROOT $ROOT)"
exit
