#!/bin/bash
set -e
unset MAKELEVEL

export JH_PKG_DIR=shadow
SRC_DIR=${JH_SRC_ARCHIVE}${JH_SRC_SUBDIRS:+/${JH_PKG_DIR}}
BUILD_DIR=${JH_BUILD_ROOT}${JH_BUILD_SUBDIRS:+/${JH_PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR
PACKAGE=shadow-4.9.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $JH_SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $JH_SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://github.com/shadow-maint/shadow/releases/download/v4.9/shadow-4.9.tar.xz ||
    wget -T 30 -t 5 ${JH_FTP_SERVER}svn/s/$PACKAGE
  fi
fi
echo "126924090caf72f3de7e9261fd4e10ac  $PACKAGE" | md5sum -c -

cd $BUILD_DIR
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf

case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     JH_UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $JH_UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       JH_UNPACKDIR=${PACKAGE%.zip}
       unzip -d $JH_UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     JH_UNPACKDIR=$JH_PKG_DIR-build
     mkdir $JH_UNPACKDIR
     cp $SRC_DIR/$PACKAGE $JH_UNPACKDIR
     ADDITIONAL="$(find . -mindepth 1 -maxdepth 1 -type l)"
     if [ -n "$ADDITIONAL" ]; then
         cp $ADDITIONAL $JH_UNPACKDIR
     fi
     ;;
esac
export JH_UNPACKDIR
cd $JH_UNPACKDIR

sed -i 's/groups$(EXEEXT) //' src/Makefile.in

find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;

sed -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
    -e 's@/var/spool/mail@/var/mail@'                 \
    -e '/PATH=/{s@/sbin:@@;s@/bin:@@}'                \
    -i etc/login.defs

sed -i.orig '/$(LIBTCB)/i $(LIBPAM) \\' libsubid/Makefile.am
sed -i "224s/rounds/min_rounds/"        libmisc/salt.c

autoreconf -fiv

./configure --sysconfdir=/etc --with-group-name-max-length=32
make
sudo -E sh << ROOT_EOF
make -j1 exec_prefix=/usr install

for libdir in /lib /usr/lib \$(find /opt -name lib); do
  find \$libdir -name \\*.la           \\
             ! -path \\*ImageMagick\\* \\
               -delete
done
ROOT_EOF
sudo /sbin/ldconfig

sudo -E sh << ROOT_EOF
sed -i 's/yes/no/' /etc/default/useradd
ROOT_EOF

sudo -E sh << ROOT_EOF
install -v -m644 /etc/login.defs /etc/login.defs.orig
for FUNCTION in FAIL_DELAY               \\
                FAILLOG_ENAB             \\
                LASTLOG_ENAB             \\
                MAIL_CHECK_ENAB          \\
                OBSCURE_CHECKS_ENAB      \\
                PORTTIME_CHECKS_ENAB     \\
                QUOTAS_ENAB              \\
                CONSOLE MOTD_FILE        \\
                FTMP_FILE NOLOGINS_FILE  \\
                ENV_HZ PASS_MIN_LEN      \\
                SU_WHEEL_ONLY            \\
                CRACKLIB_DICTPATH        \\
                PASS_CHANGE_TRIES        \\
                PASS_ALWAYS_WARN         \\
                CHFN_AUTH ENCRYPT_METHOD \\
                ENVIRON_FILE
do
    sed -i "s/^\${FUNCTION}/# &/" /etc/login.defs
done
ROOT_EOF
sudo -E sh << ROOT_EOF
cat > /etc/pam.d/login << "EOF"
# Begin /etc/pam.d/login

# Set failure delay before next prompt to 3 seconds
auth      optional    pam_faildelay.so  delay=3000000

# Check to make sure that the user is allowed to login
auth      requisite   pam_nologin.so

# Check to make sure that root is allowed to login
# Disabled by default. You will need to create /etc/securetty
# file for this module to function. See man 5 securetty.
#auth      required    pam_securetty.so

# Additional group memberships - disabled by default
#auth      optional    pam_group.so

# include system auth settings
auth      include     system-auth

# check access for the user
account   required    pam_access.so

# include system account settings
account   include     system-account

# Set default environment variables for the user
session   required    pam_env.so

# Set resource limits for the user
session   required    pam_limits.so

# Display date of last login - Disabled by default
#session   optional    pam_lastlog.so

# Display the message of the day - Disabled by default
#session   optional    pam_motd.so

# Check user's mail - Disabled by default
#session   optional    pam_mail.so      standard quiet

# include system session and password settings
session   include     system-session
password  include     system-password

# End /etc/pam.d/login
EOF
ROOT_EOF
sudo -E sh << ROOT_EOF
cat > /etc/pam.d/passwd << "EOF"
# Begin /etc/pam.d/passwd

password  include     system-password

# End /etc/pam.d/passwd
EOF
ROOT_EOF
sudo -E sh << ROOT_EOF
cat > /etc/pam.d/su << "EOF"
# Begin /etc/pam.d/su

# always allow root
auth      sufficient  pam_rootok.so

# Allow users in the wheel group to execute su without a password
# disabled by default
#auth      sufficient  pam_wheel.so trust use_uid

# include system auth settings
auth      include     system-auth

# limit su to users in the wheel group
auth      required    pam_wheel.so use_uid

# include system account settings
account   include     system-account

# Set default environment variables for the service user
session   required    pam_env.so

# include system session settings
session   include     system-session

# End /etc/pam.d/su
EOF
ROOT_EOF
sudo -E sh << ROOT_EOF
cat > /etc/pam.d/chage << "EOF"
# Begin /etc/pam.d/chage

# always allow root
auth      sufficient  pam_rootok.so

# include system auth, account, and session settings
auth      include     system-auth
account   include     system-account
session   include     system-session

# Always permit for authentication updates
password  required    pam_permit.so

# End /etc/pam.d/chage
EOF
ROOT_EOF
sudo -E sh << ROOT_EOF
for PROGRAM in chfn chgpasswd chpasswd chsh groupadd groupdel \\
               groupmems groupmod newusers useradd userdel usermod
do
    install -v -m644 /etc/pam.d/chage /etc/pam.d/\${PROGRAM}
    sed -i "s/chage/\$PROGRAM/" /etc/pam.d/\${PROGRAM}
done
ROOT_EOF
sudo -E sh << ROOT_EOF
[ -f /etc/login.access ] && mv -v /etc/login.access{,.NOUSE}
ROOT_EOF
sudo -E sh << ROOT_EOF
[ -f /etc/limits ] && mv -v /etc/limits{,.NOUSE}
ROOT_EOF

cd $BUILD_DIR
[[ -n "$JH_KEEP_FILES" ]] || sudo rm -rf $JH_UNPACKDIR unpacked

exit
